# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
jobs:
  - job: TerraformInstall
    displayName: 'Terraform Install and Deploy'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Installing Terraform'
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/windows-basic'
        backendServiceArm: 'uamanagedidentity'
        backendAzureRmOverrideSubscriptionID: 'd4795569-5a69-469c-8976-1068730d6499'
        backendAzureRmResourceGroupName: 'config-statefile-rg'
        backendAzureRmStorageAccountName: 'tfstatemrao123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/windows-basic'
        environmentServiceNameAzureRM: 'uamanagedidentity'
    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/windows-basic'
        environmentServiceNameAzureRM: 'uamanagedidentity'